-- Item pixel sizes calculated from texture files
-- Generated automatically by calculateItemPixelSizes.js

local ITEM_PX_SIZES = {
    -- Tools (special sizes)
    ["Sword"] = {x = 14, y = 14},
    ["Axe"] = {x = 12, y = 14},
    ["Shovel"] = {x = 12, y = 12},
    ["Pickaxe"] = {x = 13, y = 13},
    ["Bow"] = {x = 14, y = 14},
    ["Arrow"] = {x = 14, y = 13},

    -- Food items
    ["apple"] = {x = 12, y = 13},
    ["baked_potato"] = {x = 11, y = 13},
    ["beef"] = {x = 14, y = 10},
    ["beetroot"] = {x = 11, y = 10},
    ["beetroot_seeds"] = {x = 13, y = 13},
    ["beetroot_soup"] = {x = 12, y = 8},
    ["bone_meal"] = {x = 8, y = 15},
    ["bread"] = {x = 13, y = 11},
    ["bucket"] = {x = 10, y = 11},
    ["cake"] = {x = 14, y = 12},
    ["carrot"] = {x = 16, y = 14},
    ["chicken"] = {x = 12, y = 15},
    ["chorus_fruit"] = {x = 12, y = 13},
    ["cocoa_beans"] = {x = 8, y = 15},
    ["cod"] = {x = 13, y = 14},
    ["cod_bucket"] = {x = 10, y = 11},
    ["cooked_beef"] = {x = 14, y = 10},
    ["cooked_chicken"] = {x = 12, y = 15},
    ["cooked_cod"] = {x = 11, y = 7},
    ["cooked_mutton"] = {x = 13, y = 10},
    ["cooked_porkchop"] = {x = 13, y = 14},
    ["cooked_rabbit"] = {x = 14, y = 14},
    ["cooked_salmon"] = {x = 11, y = 7},
    ["cookie"] = {x = 14, y = 10},
    ["dried_kelp"] = {x = 14, y = 14},
    ["egg"] = {x = 8, y = 10},
    ["glistering_melon_slice"] = {x = 14, y = 14},
    ["golden_apple"] = {x = 12, y = 13},
    ["golden_carrot"] = {x = 9, y = 15},
    ["kelp"] = {x = 14, y = 14},
    ["melon_seeds"] = {x = 13, y = 13},
    ["melon_slice"] = {x = 14, y = 14},
    ["milk_bucket"] = {x = 10, y = 11},
    ["mushroom_stew"] = {x = 12, y = 9},
    ["mutton"] = {x = 13, y = 10},
    ["nether_wart"] = {x = 8, y = 12},
    ["poisonous_potato"] = {x = 11, y = 11},
    ["popped_chorus_fruit"] = {x = 12, y = 11},
    ["porkchop"] = {x = 13, y = 14},
    ["potato"] = {x = 11, y = 13},
    ["pufferfish"] = {x = 15, y = 14},
    ["pufferfish_bucket"] = {x = 12, y = 15},
    ["pumpkin_pie"] = {x = 13, y = 10},
    ["pumpkin_seeds"] = {x = 13, y = 13},
    ["rabbit"] = {x = 14, y = 14},
    ["rabbit_stew"] = {x = 12, y = 8},
    ["rotten_flesh"] = {x = 14, y = 14},
    ["salmon"] = {x = 13, y = 14},
    ["salmon_bucket"] = {x = 10, y = 12},
    ["spider_eye"] = {x = 10, y = 13},
    ["sugar"] = {x = 14, y = 14},
    ["sugar_cane"] = {x = 14, y = 16},
    ["tropical_fish"] = {x = 11, y = 12},
    ["tropical_fish_bucket"] = {x = 10, y = 12},
    ["turtle_egg"] = {x = 10, y = 11},
    ["water_bucket"] = {x = 10, y = 11},
    ["wheat"] = {x = 14, y = 15},
    ["wheat_seeds"] = {x = 13, y = 13},
}

return ITEM_PX_SIZES
